### ISSUE TITLE
Alsatian errors in projects with extra TS compiler flags

### ISSUE THREAD

**Issue by paarthenon** [alsatian-test/alsatian#209] opened 2016-11-20 05:17 UTC
I'm trying to use alsatian with a project of mine. My project has the `noUnusedLocals` and `noUnusedParameters` flags activated. Using these flags I'm unable to compile my project because of errors in alsatian.

> node_modules/alsatian/core/decorators/async-test-decorator.ts(5,47): error TS6133: 'descriptor' is declared but never used.
node_modules/alsatian/core/decorators/focus-test-decorator.ts(4,61): error TS6133: 'descriptor' is declared but never used.
node_modules/alsatian/core/decorators/ignore-test-decorator.ts(5,47): error TS6133: 'descriptor' is declared but never used.
node_modules/alsatian/core/decorators/setup-decorator.ts(4,57): error TS6133: 'descriptor' is declared but never used.
node_modules/alsatian/core/decorators/teardown-decorator.ts(4,60): error TS6133: 'descriptor' is declared but never used.
node_modules/alsatian/core/decorators/test-case-decorator.ts(5,45): error TS6133: 'descriptor' is declared but never used.
node_modules/alsatian/core/decorators/test-decorator.ts(5,45): error TS6133: 'descriptor' is declared but never used.
node_modules/alsatian/core/decorators/timeout-decorator.ts(9,45): error TS6133: 'descriptor' is declared but never used.
node_modules/alsatian/core/expect.ts(2,4): error TS6133: 'MatchError' is declared but never used.
node_modules/alsatian/core/running/test-item.ts(45,39): error TS6133: 'reject' is declared but never used.
node_modules/alsatian/core/running/test-item.ts(63,41): error TS6133: 'reject' is declared but never used.
node_modules/alsatian/core/running/test-item.ts(75,41): error TS6133: 'reject' is declared but never used.
node_modules/alsatian/core/running/test-runner.ts(1,10): error TS6133: 'ITestFixture' is declared but never used.
node_modules/alsatian/core/running/test-runner.ts(3,10): error TS6133: 'MatchError' is declared but never used.
node_modules/alsatian/core/running/test-runner.ts(3,38): error TS6133: 'TestFixtureResults' is declared but never used.
node_modules/alsatian/core/running/test-runner.ts(3,58): error TS6133: 'TestResults' is declared but never used.
node_modules/alsatian/core/running/test-runner.ts(3,98): error TS6133: 'TestTimeoutError' is declared but never used.
node_modules/alsatian/core/running/test-runner.ts(5,10): error TS6133: 'TestItem' is declared but never used.
node_modules/alsatian/core/running/test-runner.ts(41,52): error TS6133: 'reject' is declared but never used.

I noticed that alsatian publishes the .ts files directly. Is this the recommended approach? Other projects I've seen seem to publish the generated .js files along with the generated .d.ts for their typings. I believe doing that would avoid this issue.

**Comment by jamesrichford** [comment] 2016-11-20 13:45
Hey @paarthk,

Good find! I can confirm this is an issue.

The reason for adding the .ts files to the distribution is so that alsatian is debuggable locally. Perhaps though, if this is going to cause issues like this it's worth removing. Do you think as a user you'd ever want to debug Alsatian directly to see whether the issue is with your own tests or Alsatian itself or just raise an issue directly here?

@Jameskmonger same question as above, what are your thoughts about debugging?

Thanks for using Alsatian :)

James

**Comment by paarthk** [comment] 2016-11-20 15:36
hey @jamesrichford thanks for the quick response!

I think I'm a little more willing to step into my dependencies than the average bear. I'm used to looking at their source code to figure things out so having the .ts files be part of the typings package doesn't change much for me. If I needed to poke at a particularly large or complex one, I typically create a dummy project to see where things are messing up to isolate the issue. I don't think users would miss much at all if the .ts files were gone. 

Alternatively, perhaps a debug form of the project as a separate npm package that follows the same module name would work? Perhaps there's some way to be clever about map files and achieve this?

That being said, I'm not your target audience for this so take that opinion with a grain of salt. My current project is a chrome extension and I haven't been doing runtime debugging in node anyway.

Paarth

**Comment by jamesrichford** [comment] 2016-11-20 16:26
Well target audience is any TypeScript users (and maybe JavaScript in the future) so absolutely you're use case and opinion is important! :)

Due a release so I'll include this change in it. As in all likelihood anyone with a problem is welcome to raise an issue and I can help with the debugging / it can be installed from GitHub with the source :)

It's my pleasure to respond quickly, any other issues or questions in the future feel free to open a new ticket :) other than this how has your experience so far been with Alsatian?

Thanks,

James

**Comment by paarthk** [comment] 2016-11-20 16:54
Thanks @jamesrichford. To be honest this has been my only experience with Alsatian (I'm attempting to add tests to an existing project and immediately ran into the compile errors) so I don't have a lot of feedback for you just yet. FWIW the issue process has been pleasant. I'll make sure to pass on my impressions once I have a better sense of the project.

**Comment by jamesrichford** [comment] 2016-11-21 09:04
Hey there Paarth,

Just published beta.3 and this seems to have resolved the issue. If you'd like to have a check and confirm that'd be ace then we can close this issue :)

Thanks,

James

**Comment by Jameskmonger** [comment] 2016-11-21 12:09
Hey @jamesrichford,

In my opinion I think we should avoid distributing anything other than the executable code (not TS) - ideally it should be bundled and minified too to make it as small as possible.

My only exception to this is I think it can be valuable to distribute the tests and source (`.js` only) so that the user can then open it and type `npm install && npm test` to see if anything is broken - but realistically there will be little benefit from this because we have CI in place so they should never have a broken test in Alsatian as a dependency.

**Comment by jamesrichford** [comment] 2016-11-21 12:14
@Jameskmonger good news, thy will be done it's in beta.3 :)

You've preempted me on the tests, this is something that we'll reserve for CI because if it passes in CI it's most likely to pass in the user's local so little point in giving them extra useless stuff.

**Comment by Jameskmonger** [comment] 2016-11-22 17:47
Closing this as no longer an issue. Reopen it if you disagree @jamesrichford, @paarthenon.

Thank you for logging!

**Closed by Jameskmonger** 2016-11-22 17:47 UTC
Labels: bug
