### ISSUE TITLE
Expect output or test runner is not showing valures which failed

### ISSUE THREAD

**Issue by tenuki** [alsatian-test/alsatian#464] opened 2018-05-17 20:40 UTC
When I run a test and actual value doesnt match expected, it would be expected those values to be shown.

```
import { AsyncTest, Expect, Test, TestCase, TestFixture } from "alsatian";

@TestFixture("whatever you'd like to call the fixture")
export class SetOfTests {
    @TestCase(3, 3, 6)
    @TestCase(3, 3, 7)
    @Test("addition tests")
    public addTest(firstNumber: number, secondNumber: number, expectedSum: number) {
        Expect(firstNumber + secondNumber).toBe(expectedSum);
    }
}
```

Its ouput is:
```
$ npm test tests/mytest.spec.ts 

> sample-test@0.0.1 test ../samples
> ts-node ../util/testrunner.ts "tests/mytest.spec.ts"

whatever you'd like to call the fixture
addition tests ( 3, 3, 7 )
|====================|

Pass: 1/2
Fail: 1/2
Ignore: 0/2

FAIL: addition tests ( 3, 3, 7 )
The test threw an unhandled error.
Expected: no unhandled errors to be thrown
  Actual: an unhandled error
npm ERR! Test failed.  See above for more details.
```
I would expect output to be:

```
FAIL: addition tests ( 3, 3, 7 )
The test threw an unhandled error.
Expected: 7
  Actual: 6
npm ERR! Test failed.  See above for more details.
```

My runner is simply:

```
import { TapBark } from "tap-bark";
import { TestSet, TestRunner } from "alsatian";
import { GlobHelper, TestLoader } from "alsatian/core";

async function do_test(test_set, testsFileLocations) {
  try {
    test_set.addTestsFromFiles(testsFileLocations);
    return true
  } catch {
    console.log("Error processing: " + testsFileLocations )
  }
  return false
}

export class SafeFileRequirer {
  public static createSafeTestSet() {
    return new TestSet(new TestLoader(new SafeFileRequirer()), new GlobHelper());
  }

  public require(requirePath: string): any {
    try {
      return require(requirePath);
    } catch {
      console.log("Can't load: " + requirePath + " !")
      console.log("")
      return {}
    }
  }
}

(async () =>
{
  const testSet = SafeFileRequirer.createSafeTestSet()
  let idx = 2
  let empty = true
  while (idx<process.argv.length) {
    
    let filename = process.argv[idx]
    console.log("adding: "+filename)
    if (do_test(testSet, filename)) {
      empty = false
    }
    idx+=1
  }

  if(empty) {
    do_test(testSet, './**/*.spec.ts')
  }

  const testRunner = new TestRunner();

  testRunner.outputStream
    .pipe(TapBark.create().getPipeable())
    .pipe(process.stdout);

  await testRunner.run(testSet);
})().catch(e =>
{
  console.error(e);
  process.exit(1);
});
```

**Comment by Jameskmonger** [comment] 2018-05-18 09:41
Hi @tenuki, thanks for reporting this and sorry you're having trouble using Alsatian!

From looking at the log, it looks like it's behaving as though `Expect(...).not.toThrowError` has been used (from the `Expected: no unhandled errors to be thrown`).

@jamesadarich any idea?

**Comment by jamesadarich** [comment] 2018-05-18 10:56
Strange, I'm away from my computer at the moment so I can't test it.

@tenuki which versions of typescript, Alsatian and node are you using. Also are you using ts-node?

**Comment by tenuki** [comment] 2018-05-18 17:00
Thanks for the fast answer!

@jamesadarich : 

alsatian@2.2.1
typescript@2.8.3
ts-node@3.3.0
node v8.11.1

**Comment by jamesadarich** [comment] 2018-05-18 19:48
Strange, from what I can see on my phone this looks like it should work. I'll have to have a peek when I get back to my computer unfortunately I'm away at the moment. Should be able to look on Tuesday. Sorry about the delay on that.

Maybe worth a debug with vsc if you're using that to see where it's throwing from.

**Comment by tenuki** [comment] 2018-05-18 20:05
Thanks I will!

**Comment by tenuki** [comment] 2018-05-20 22:55
I couldn't get to debug alsatian test-lib typescript code :-(

**Comment by pathurs** [comment] 2018-07-18 09:23
Hi @tenuki,

I've tried this locally and cannot reproduce the issue.

![image](https://user-images.githubusercontent.com/3084995/42872355-140f1e48-8ac0-11e8-804f-5f8eb2ab93be.png)

```
whatever you'd like to call the fixture
addition tests ( 3, 3, 7 )
|====================|

Pass: 1/2
Fail: 1/2
Ignore: 0/2

FAIL: addition tests ( 3, 3, 7 )
Expected 6 to be 7.
Expected: 7
  Actual: 6
```

**Comment by tenuki** [comment] 2018-07-18 12:15
Thanks, I'll try to re-reproduce it and comment.

**Comment by jamesadarich** [comment] 2018-10-19 20:40
Since we can't reproduce closing for now, please reopen or create a new issue if you manage to reproduce this @tenuki  :)

**Closed by jamesadarich** 2018-10-19 20:40 UTC
